### ISSUE TITLE
Not able to reproduce the results for "Ranger-Mish-ImageWoof-SelfAttention.ipynb"

### ISSUE THREAD

**Issue by saurabh502** [lessw2020/Ranger-Mish-ImageWoof-5#3]
Hi I tried running **Ranger-Mish-ImageWoof-SelfAttention.ipynb** note book but the results which I am getting is not same as present in the notebook. I am using exact same setting and running the notebook on Kaggle kernel. Below is example for **Ranger + SimpleSelfAttention + MXResnet + Flatten Anneal**

```
epoch	train_loss	valid_loss	accuracy	top_k_accuracy	time
0	1.934860	1.840945	0.386000	0.868000	01:16
1	1.671709	1.774384	0.416000	0.900000	01:16
2	1.494775	1.393782	0.608000	0.938000	01:16
3	1.388411	1.308814	0.670000	0.944000	01:16
4	1.191175	1.121989	0.742000	0.976000	01:16
```
I am not getting similar results for all different setups.

**Comment by lessw2020** [comment]
HI @saurabh502 ,,
the results above are in line with ours for ImageWoof, 5 epoch, 128px:
128 | 5 | 74.97
You'll see +/- 1% or so from run to run, the above is our average.

Are you perhaps comparing this score to the ImageNette score (the first score shown on github)?  ImageNette is much easier than Woof and so the score is much higher - around 89% or so.
Scroll down on that page to see the Woof scores.
Hope that helps!

**Comment by lessw2020** [comment]
Your results here are spot on for Woof dataset and I'm quite sure that you may have seen the Nette database score when pulling up the leaderboards...so closing this for now :)

**Comment by lessw2020** [comment]
Hi @saurabh502  - well looks like this might have been our fault.
the code in train.py was broken so if you ran with woof 0  (which means load ImageNette)...you still got ImageWoof database!
    if woof:
        path = URLs.IMAGEWOOF    # if woof 
    else:
        path = URLs.IMAGENETTE
So that might explain your issue here....apologies as I thought you were just looking at the wrong leaderboard for ImageWoof.
Anyway, it's fixed now in train.py and you should be able to replicate our ImageNette scores now.
Best regards,
Less
